version: "3.9"

networks:
#  jhe_sso_two:
#    external:
#      name: jhe_sso_two
  dk_sso_one:
    name: dk_sso_one
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis
      - mysql
    container_name: dk_sso_one_server
    networks:
      - dk_sso_one
#      - jhe_sso_two
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - dk_sso_one
#     - jhe_sso_two
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    hostname: mysql_one_server
    env_file:
      - ./env/mysql.env
    networks:
      - dk_sso_one
    container_name: mysql_one_server
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - dk_sso_one
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - dk_sso_one
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
    networks:
      - dk_sso_one
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    hostname: phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8890:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - dk_sso_one